--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/SimpleSleep
build-by-default: true
branches:
- master
projects:
  SimpleSleep:
    path: ""
    icon: "assets/logo.PNG"
    libs:
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^2.1
...
