---
######## SimpleSleep Configuration File ########
# Author: brokiem (https://github.com/brokiem)
# Source code: https://github.com/brokiem/SimpleSleep

# Don't edit this version
config-version: 1.0

# Enabled world for sleep to trigger event
enable-all-worlds: true

# If "enable-all-worlds" is false, set your folder world name below
enabled-worlds:
  - "world"
  - "world2"

# Sleep duration in tick (20 ticks = 1 second)
sleep-duration: 100 # mean 5 seconds

# Minimum players to change time
minimal-players: 1

# Message type (Value: "message", "actionbar")
message-type: "actionbar"

# Sleep Messages
on-enter-bed-message: "{player} is sleeping!"
...